### ISSUE TITLE
Make basic API endpoints for getting all Branches 

### ISSUE THREAD

**Issue by FinnbarHome** [Nintails-TF/ncr-agile-wombo#72]
Feature Description:
Make basic API endpoints for getting all Branches 

Problem and Motivation:
So the API endpoints can be used by the backend etc

Acceptance Criteria:
List of conditions that must be met for the feature to be considered complete.

- [x] Connection to db successful 
- [x] All crud commands for endpoints complete
- [x] Data manipulated correctly with no errors

Testing:
- [x] Has the code been tested and reviewed?

**Comment by Nintails-TF** [comment]
These have been solved in PRs #72 and #100
