### ISSUE TITLE
Fix HTML Validation

### ISSUE THREAD

**Issue by KyleTait01** [Nintails-TF/ncr-agile-wombo#97]
Feature Description:
There are HTML validation errors showing after running through an HTML validation checker

Problem and Motivation:
This ensures HTML standards are being followed and there are no risk of HTML errors affecting the website

Acceptance Criteria:
No HTML validation errors

- [x] Fix HTML validation errors

Testing:
- [x] Has the code been tested and reviewed?

**Comment by Nintails-TF** [comment]
Validation of HTML has been solved
